version: '3.8'
services:
  db_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dasdsadas
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: muser
      MYSQL_PASSWORD: 9iffdsssda
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
volumes:
  db_data:
